### ISSUE TITLE
example.cpp trackable should use public inheritance

### ISSUE THREAD

**Issue by NoAvailableAlias** [tripleslash/rocket#5]
Hello, I'm currently integrating your rocket lib into the signal-slot-benchmarks and encountered an issue with trackable not tracking connections unless public inheritance is used.

https://github.com/tripleslash/rocket/blob/master/example.cpp#L5

Should use public inheritance instead of private or else it will not track slots at runtime.

**Comment by tripleslash** [comment]
Hey, thanks a lot for your work!
The example works like this because it is a struct and therefore has public inheritance by default. However you're right that this is probably confusing and should be changed to make it clear that it has to use public inheritance.

Cheers!
