### ISSUE TITLE
rocket::thread_safe_signal::operator() argument by reference issue

### ISSUE THREAD

**Issue by NoAvailableAlias** [tripleslash/rocket#6]
Hello, I have integrated your rocket lib into the [signal-slot-benchmarks](https://github.com/NoAvailableAlias/signal-slot-benchmarks/) and I'm encountering an msvc compilation issue when attempting to integrate the rocket::thread_safe_signal into the benchmark.

[Here is the issue](https://github.com/NoAvailableAlias/signal-slot-benchmarks/blob/master/benchmark/hpp/benchmark_tsr.hpp#L29) as well as the exact error message and line number that visual studio is reporting.

Note that using rocket::signal in the [single thread version](https://github.com/NoAvailableAlias/signal-slot-benchmarks/blob/master/benchmark/hpp/benchmark_tsr_st.hpp#L26) of the rocket benchmark compiles and runs fine.

(here are the msvc [benchmark results](https://github.com/NoAvailableAlias/signal-slot-benchmarks/tree/master/results/benchmarks_msvc))

**Comment by tripleslash** [comment]
Hey, thanks a lot for your work and for reporting this!

This was a nasty issue to fix properly because the library supports executing slots in different threads. To make that happen I needed to copy the arguments. Now this is done conditionally depending if the argument is a non-const reference.

Cheers

**Comment by NoAvailableAlias** [comment]
No problem, the lib has been updated in the benchmarks.

(here are the msvc [benchmark results](https://github.com/NoAvailableAlias/signal-slot-benchmarks/tree/master/results/benchmarks_msvc))
